### ISSUE TITLE
enter grades directly, without SpeedGrader/gradebook?

### ISSUE THREAD

**Issue by lsloan** [longhornopen/canvas-peer-grade-calculator#15]
This is a two-in-one request…

1. Add a column for the grade that should appear in the gradebook.  It may be pre-populated with the values entered by the peer or maybe a button could be added to do that on demand.  Having a column for the final grade would let the instructor override the grade from the peer, if that were necessary.  (E.g., maybe the peer graded too harshly, too generously, or not at all.)
2. Send the grades directly to the gradebook rather than exporting the data to CSV.

This request is partly motivated by the way peer reviews are currently done at UMich.  Instructors usually do not use peer grading here.  They're interested in using this app for entering the grades.  For example, a course has several TAs, one for each section.  The TAs would use this app to see the authors' submissions and the reviewers' comments, then enter the grades, as appropriate.

The other motivation is that Canvas' SpeedGrader and gradebook are very slow tools to work with, especially when courses have over 1200 students.  If this app could do this, combined with the single-section selection suggested in #13, then it would be much more convenient for instructors to enter grades.

We hope this is not outside the scope of the project.

**Comment by chrispittman** [comment]
This app was designed as a peer grade calculator, and making it also be a competitor to Canvas's SpeedGrader for classes that don't use peer grading at all increases the scope a lot.  We'd need to either:
* somehow get faster responses from Canvas's APIs than Canvas's Speedgrader is, or
* add some pretty significant installation dependencies (a database to write grade updates to, and a separate queue-worker server to read those updates and transmit them to Canvas in the background.

Every time we've asked Instructure how to handle Speedgrader's slowness in our own large courses, their response has been to generate a CSV and upload it rather than trying to do it live, which is why we're taking the approach we are here.

**Comment by lsloan** [comment]
OK.  Thanks for considering it, @chrispittman.
